[[linter]]
code = 'CPPCHECK'
include_patterns = [
    '**/*.c',
    '**/*.cc',
    '**/*.cpp',
    '**/*.cxx',
    '**/*.h',
    '**/*.hh',
    '**/*.hpp',
    '**/*.hxx',
]
exclude_patterns = []
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'cppcheck_linter',
    '--enable=warning,style,performance,portability',
    '--extra-arg=--inline-suppr',
    '--',
    '@{{PATHSFILE}}',
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'cppcheck-wheel==1.5.1',
    'defusedxml>=0.7.1',
]
