[[linter]]
code = 'REFURB'
include_patterns = [
    '**/*.py',
]
exclude_patterns = []
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'refurb_linter',
    '--config-file=pyproject.toml',
    '--show-disable',
    '--severity=FURB101:advice',
    '--severity=FURB102:warning',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'refurb==1.10.0',
]
