name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install
          poetry run lintrunner init
      - name: Run pytest
        run: |
          PY_IGNORE_IMPORTMISMATCH=1 poetry run pytest --doctest-modules
